- name: Add the worker to the swarm
  community.general.docker_swarm:
    state: join
    advertise_addr: swarm-worker
    join_token: "{{ hostvars['swarm-manager']['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ 'swarm-manager:2377' ]