- name: "Install dependencies"
  apt:
    name: "{{ item }}"
    state: latest 
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python3
    - python3-pip
    - python-setuptools
  tags: docker
- name: Get Docker key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker Packages to Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable
    tags: docker

- name: "Install Docker"
  apt:
    name: docker-ce
    state: latest
    update_cache: true
- name: Start Docker service
  service:
    name: docker
    state: started
- name: dependencies
  apt:
    name: python3-pip
    state: latest
- name: pip docker
  pip:
    executable: pip3
    name: docker